# Generated by Django 4.1.7 on 2023-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=150, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('total_expected_interest_amount', models.FloatField(blank=True, null=True)),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('expected_interest_amount', models.FloatField(blank=True, null=True)),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('expected_irr', models.FloatField(blank=True, null=True)),
                ('realized_irr', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_identifier', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('type', 'loan_identifier', 'amount', 'reference_date')},
            },
        ),
    ]
